# Generated by Django 3.0.2 on 2020-01-30 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='AboutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ordering', models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text="an optional image for the 'about' section.", null=True, upload_to='', verbose_name='image')),
                ('organizer', models.ForeignKey(help_text="the event we're giving the info about.", on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='events.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'about event',
                'verbose_name_plural': 'abouts on events',
                'ordering': ['organizer', 'ordering'],
            },
        ),
    ]
