# Generated by Django 3.0.2 on 2020-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200130_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutevent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='slug',
        ),
    ]
