# Generated by Django 2.2 on 2020-04-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20200401_0913'),
        ('events', '0003_auto_20200131_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutevent',
            options={'ordering': ['event', 'ordering'], 'verbose_name': 'about event', 'verbose_name_plural': 'abouts on events'},
        ),
        migrations.RenameField(
            model_name='aboutevent',
            old_name='organizer',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='links',
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Link')),
                ('event', models.ForeignKey(help_text='to which event does the link belong?', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event link',
                'verbose_name_plural': 'event links',
                'ordering': ['event', 'ordering', 'created_at'],
            },
            bases=('utils.link',),
        ),
    ]
