# Generated by Django 2.2.10 on 2021-10-12 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.TextField(blank=True, null=True, verbose_name='conversation id')),
                ('parties', models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='MatchmakingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_matched', models.DateTimeField(blank=True, null=True, verbose_name='date matched')),
                ('date_expired', models.DateTimeField(blank=True, null=True, verbose_name='date expired')),
            ],
        ),
    ]
