# Generated by Django 2.2.10 on 2021-07-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
        ('accounts', '0002_auto_20210420_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_field',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='education field'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='networking.Interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='job title'),
        ),
    ]
