# Generated by Django 2.2.10 on 2021-08-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='linkedin ID'),
        ),
    ]
