# Generated by Django 2.2 on 2020-06-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0006_organizer_main_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.ImageField(blank=True, help_text='an icon for the news', null=True, upload_to='', verbose_name='icon')),
                ('organizer', models.ForeignKey(help_text='to which organizer does the news belong?', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='organizers.Organizer', verbose_name='organizer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
