# Generated by Django 2.2 on 2020-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_fix_typo_in_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, help_text='news date', null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='news',
            name='extra_link',
            field=models.URLField(blank=True, help_text='any extra link related to the talk?', null=True, verbose_name='extra link'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='an image for the news.', null=True, upload_to='', verbose_name='image'),
        ),
    ]
