# Generated by Django 3.0.2 on 2020-01-30 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, help_text='an optional title describing the link.', max_length=255, null=True, verbose_name='title')),
                ('role', models.SlugField(blank=True, help_text='an optional slug, describing the link for other programs, such as applications.', max_length=31, null=True, verbose_name='role')),
                ('url', models.URLField(help_text='the url address for the link.', verbose_name='url')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['created_at'],
            },
        ),
    ]
