# Generated by Django 3.0.2 on 2020-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_link_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['ordering', 'created_at'], 'verbose_name': 'link', 'verbose_name_plural': 'links'},
        ),
        migrations.AddField(
            model_name='link',
            name='ordering',
            field=models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering'),
        ),
    ]
