# Generated by Django 3.0.2 on 2020-01-30 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name of the current organizer. e.g. TEDxTehran.', max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='a few paragraphs of info about the current organizer.', null=True, verbose_name='description')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'organizer',
                'verbose_name_plural': 'organizers',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(help_text="the organizer to whom's events user has access.", on_delete=django.db.models.deletion.CASCADE, related_name='organizer_accounts', to='organizers.Organizer', verbose_name='organizer')),
                ('user', models.OneToOneField(help_text="a user who has access to organizer's events", on_delete=django.db.models.deletion.CASCADE, related_name='organizer_account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organizer account',
                'verbose_name_plural': 'organizers accounts',
                'ordering': ['organizer', 'user'],
            },
        ),
    ]
