# Generated by Django 3.0.2 on 2020-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_auto_20200130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(blank=True, help_text="organizer's logo", null=True, upload_to='', verbose_name='logo'),
        ),
    ]
