# Generated by Django 3.0.2 on 2020-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_auto_20200130_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutorganizer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organizeraccount',
            name='slug',
        ),
    ]
