# Generated by Django 2.2 on 2020-04-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200401_1133'),
        ('organizers', '0005_auto_20200131_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='main_event',
            field=models.OneToOneField(blank=True, help_text='which event is currently the main event for this organizer?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.Event', verbose_name='main event'),
        ),
    ]
