# Generated by Django 3.0.2 on 2020-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
