# Generated by Django 2.2 on 2020-10-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_venue_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='adddress',
            new_name='adress',
        ),
    ]
