# Generated by Django 2.2 on 2020-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_fix_typo_in_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='adress',
            new_name='address',
        ),
    ]
