# Generated by Django 3.0.2 on 2020-01-31 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timelines', '0002_auto_20200131_1218'),
        ('organizers', '0004_auto_20200130_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='a thumbnail image for the speaker.', null=True, upload_to='', verbose_name='image')),
                ('organizer', models.ForeignKey(help_text='to which organizer does the speaker belong?', on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='organizers.Organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'speaker',
                'verbose_name_plural': 'speakers',
                'ordering': ['organizer', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timelines.Section')),
                ('video_link', models.URLField(blank=True, help_text='video link?', null=True, verbose_name='video link')),
                ('extra_link', models.URLField(blank=True, help_text='any extra link related to the talk?', null=True, verbose_name='extra link')),
                ('speakers', models.ManyToManyField(help_text='which speaker(s) will be giving the talk?', related_name='speakers', to='talks.Speaker', verbose_name='speakers')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
                'ordering': ['event', 'ordering', 'start_time', 'title'],
            },
            bases=('timelines.section',),
        ),
    ]
