# Generated by Django 2.2 on 2020-04-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20200401_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
