# Generated by Django 2.2 on 2020-04-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_auto_20200401_1537'),
        ('talks', '0004_delete_talk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('video_link', models.URLField(blank=True, help_text='video link?', null=True, verbose_name='video link')),
                ('extra_link', models.URLField(blank=True, help_text='any extra link related to the talk?', null=True, verbose_name='extra link')),
                ('section', models.OneToOneField(help_text='on which event section do we have the talk?', on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='timelines.Section', verbose_name='section')),
                ('speakers', models.ManyToManyField(help_text='which speaker(s) will be giving the talk?', related_name='speakers', to='talks.Speaker', verbose_name='speakers')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
                'ordering': ['section'],
            },
        ),
    ]
