# Generated by Django 2.2 on 2020-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='talk',
            name='title',
            field=models.CharField(default='dsf', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
