# Generated by Django 2.2 on 2020-10-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200401_1133'),
        ('talks', '0006_auto_20200626_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(help_text='to which event does the speaker belong?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.Event', verbose_name='event'),
        ),
    ]
