# Generated by Django 2.2 on 2020-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_speaker_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='aparat_link',
            field=models.URLField(blank=True, help_text='Aparat link', null=True, verbose_name='Aparat link'),
        ),
    ]
