# Generated by Django 2.2 on 2020-10-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0006_organizer_main_event'),
        ('events', '0004_auto_20200401_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'sponsor type',
                'verbose_name_plural': 'sponsor types',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='a thumbnail image for the sponsor.', null=True, upload_to='', verbose_name='image')),
                ('logo', models.ImageField(blank=True, help_text='logo of the sponsor.', null=True, upload_to='', verbose_name='logo')),
                ('event', models.ManyToManyField(help_text='to which event does the sponsor belong?', related_name='sponsors', to='events.Event', verbose_name='event')),
                ('organizer', models.ManyToManyField(help_text='to which organizer does the sponsor belong?', related_name='sponsors', to='organizers.Organizer', verbose_name='organizer')),
                ('type', models.ForeignKey(help_text='what is the type of this sponsor', on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='sponsors.SponsorsType', verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
