# Generated by Django 2.2 on 2020-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsors_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorstype',
            name='ordering',
            field=models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering'),
        ),
    ]
