# Generated by Django 3.0.2 on 2020-01-31 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0004_auto_20200130_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ordering', models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('organizer', models.ForeignKey(help_text='to which organizer does the album belong?', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='organizers.Organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ordering', models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering')),
                ('thumbnail', models.ImageField(help_text='a thumbnail to show in album.', upload_to='', verbose_name='thumbnail')),
                ('link', models.URLField(blank=True, help_text='an external link to the media.', null=True, verbose_name='link')),
                ('caption', models.TextField(blank=True, help_text='an optional text, describing the media.', null=True, verbose_name='caption')),
                ('video', models.FileField(blank=True, help_text="the main video file, if we're saving in in our own system.", null=True, upload_to='', verbose_name='image')),
                ('album', models.ForeignKey(help_text='to which album does the media belong?', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='gallery.Album', verbose_name='album')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['album', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ordering', models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering')),
                ('thumbnail', models.ImageField(help_text='a thumbnail to show in album.', upload_to='', verbose_name='thumbnail')),
                ('link', models.URLField(blank=True, help_text='an external link to the media.', null=True, verbose_name='link')),
                ('caption', models.TextField(blank=True, help_text='an optional text, describing the media.', null=True, verbose_name='caption')),
                ('image', models.ImageField(blank=True, help_text="the main photo file, if we're saving in in our own system.", null=True, upload_to='', verbose_name='image')),
                ('album', models.ForeignKey(help_text='to which album does the media belong?', on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gallery.Album', verbose_name='album')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['album', 'ordering'],
            },
        ),
    ]
