# Generated by Django 3.0.2 on 2020-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
