# Generated by Django 2.2 on 2020-04-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200401_1133'),
        ('gallery', '0002_auto_20200131_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event',
            field=models.ForeignKey(blank=True, help_text='to which event does the album belong?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='events.Event', verbose_name='event'),
        ),
    ]
