# Generated by Django 2.2 on 2020-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, help_text="the main video file, if we're saving in in our own system.", null=True, upload_to='', verbose_name='video'),
        ),
    ]
