# Generated by Django 3.0.2 on 2020-01-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizers', '0005_auto_20200131_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='is the application currently active and functional?', verbose_name='is active')),
                ('organizer', models.ForeignKey(help_text='to which organizer does this app belong?', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organizers.Organizer', verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['organizer', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='a unique key sent in header to authorize the application.', unique=True, verbose_name='key')),
                ('active', models.BooleanField(default=True, help_text='is the application token currently active and functional?', verbose_name='active')),
                ('application', models.ForeignKey(help_text='to which application does this key belong?', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='applications.Application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'Application Token',
                'verbose_name_plural': 'Application Tokens',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('application', models.ForeignKey(help_text='which application user has used?', on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='applications.Application', verbose_name='application')),
                ('user', models.ForeignKey(blank=True, help_text='which user (if authenticated) has used the system?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'application hit',
                'verbose_name_plural': 'application hits',
            },
        ),
    ]
