# Generated by Django 3.0.2 on 2020-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_active',
        ),
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True, help_text='is the application currently active and functional?', verbose_name='active'),
        ),
    ]
