# Generated by Django 2.2 on 2020-04-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_auto_20200131_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sessions',
        ),
        migrations.AddField(
            model_name='section',
            name='session',
            field=models.ForeignKey(default=1, help_text='in which session this section will be held?', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='timelines.Session', verbose_name='session'),
            preserve_default=False,
        ),
    ]
