# Generated by Django 2.2 on 2020-04-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_auto_20200401_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['session', 'start_time', 'ordering'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='event',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic'), ('talk', 'Talks'), ('performance', 'Performance'), ('activity', 'Activity'), ('entertainment', 'Entertainment')], default='generic', help_text="shows type of this program section, whether it's a generic section, a talk or performance, an activity, or else.", max_length=31, verbose_name='type'),
        ),
    ]
