# Generated by Django 2.2.10 on 2021-04-20 18:31

import apps.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.authentication.models._generate_random_token, max_length=64, unique=True, verbose_name='token')),
                ('verification_code', models.CharField(blank=True, default=apps.authentication.models._generate_code, max_length=32, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_succeeded', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
