name: Docker Image CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: event-app-core

jobs:


  build:
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION_BRANCH=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Use Docker `latest` tag convention
          [ "$VERSION_BRANCH" == "master" ] && VERSION_BRANCH=latest

          VERSION_SHA=$(echo $GITHUB_SHA | head -c7)

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION_SHA=$VERSION_SHA" >> $GITHUB_ENV
          echo "VERSION_BRANCH=$VERSION_BRANCH" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_ID }}:${{ env.VERSION_BRANCH }}
            ${{ env.IMAGE_ID }}:${{ env.VERSION_SHA }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
