# Generated by Django 2.2 on 2020-04-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_auto_20200401_1133'),
        ('organizers', '0006_organizer_main_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ordering', models.SmallIntegerField(default=0, help_text="the object's position, in relation to it's siblings.", verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, help_text='a thumbnail to show in album.', null=True, upload_to='', verbose_name='thumbnail')),
                ('summary', models.CharField(blank=True, help_text='a short summary for the news.', max_length=511, null=True, verbose_name='summary')),
                ('link', models.URLField(blank=True, help_text='an external link for the news item.', null=True, verbose_name='link')),
                ('event', models.ForeignKey(blank=True, help_text='to which event does the news belong?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='events.Event', verbose_name='event')),
                ('organizer', models.ForeignKey(help_text='to which organizer does the news belong?', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='organizers.Organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['ordering', 'title'],
            },
        ),
    ]
